config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def index
    @tasks = Task.all
  end

  def show
  end

  def edit
  end

  def update
    @task.update(task_params)
    redirect_to tasks_path
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application','//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.no-icons.min.css' %>
    <%= stylesheet_link_tag 'application','//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css' %>
    <%= stylesheet_link_tag 'application','https://fonts.googleapis.com/css?family=Roboto&display=swap' %>
    <%= stylesheet_link_tag 'application','https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<div class="container p-10">
  <%= form_for(@task) do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control'  %>
    </div>
    <div class="form-group">
      <%= f.label :details %>
      <%= f.text_field :details, class: 'form-control'  %>
    </div>
    <div class="form-group">
      <%= f.label :completed %>
      <%= f.check_box :completed, {}, true, false %>
    </div>
    <%= f.submit class: 'btn btn-primary'%>
  <% end %>
  <%= link_to "Back to list", tasks_path %>
</div>

app/views/tasks/index.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col">
      <div class="card">
      <h1>TASKS</h1>
      <div class=task-container>
        <% @tasks.each do |task| %>
          <div class="task-card">
          <% if task.completed == true %>
            <input type="checkbox" checked>
          <% else %>
            <input type="checkbox">
          <% end %>
          <%= link_to task.title, task_path(task) %>
          <%= link_to "Delete", task_path(task),
            method: :delete
          %>
          </div>
        <% end %>
      </div>
      <%= link_to "Add a new task", new_task_url %>
      </div>
    </div>
  </div>
</div>

app/views/tasks/new.html.erb
<div class="container">
  <%= form_for(@task) do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control'  %>
    </div>
    <div class="form-group">
      <%= f.label :details %>
      <%= f.text_field :details, class: 'form-control'  %>
    </div>

    <%= f.submit class: 'btn btn-primary'%>
  <% end %>
  <%= link_to "Back to list", tasks_path %>
</div>

app/views/tasks/show.html.erb
<div class="container">
  <h1>
    <%= @task.details %>
  </h1>
  <% if @task.completed == true %>
    <p>This task is completed</p>
  <% else %>
    <p>This task is not completed</p>
  <% end %>

  <%= link_to "Edit this task", edit_task_url %>
  <%= link_to "Back to list", tasks_path %>
</div>